spring:
  application:
    name: spring-boot-vuejs
  main:
    banner-mode: "off"
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: testDb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration